import turtle
kame = turtle.Turtle()
kame.shape("turtle")
kame.shapesize(2,2,3)
kame.forward(150)
kame.right(90)
kame.left(180)
kame.circle(150)
kame.undo()
kame.home()
kame.clear()
print(kame.getscreen().window_width())
print(kame.getscreen().window_height())
print(kame.position())
kame.goto(150,200)
kame.undo()
print(kame.position())
print(kame.distance(0,0))
kame.penup()
kame.circle(150)
print(kame.isdown())
kame.pendown()
kame.circle(150)
kame.home()
kame.clear()
for i in range(5):
    kame.forward(200)
    kame.left(144)
kame.home()
kame.clear()
for i in range(6):
    kame.forward(100)
    kame.left(60)
import random
random.randint(1,360)
kame.home()
kame.clear()
kame.penup()
kame.forward(200)
kame.left(90)
kame.pendown()
kame.circle(200)
kame.penup()
kame.home()
kame.pendown()
while kame.distance(0,0)<200:
    kame.left(random.randint(1,360))
    kame.forward(15)
kame.home()
kame.clear()
kame.penup()
kame.forward(200)
kame.left(90)
kame.pendown()
kame.circle(200)
kame.penup()
kame.home()
while True:
    kame.left(random.randint(1,360))
    kame.forward(15)
    if kame.distance(0,0)>200:
        kame.undo()
turtle.done()
